version: "3"
services:
  db:
    image: mongo
    restart: always
  gui:
    image: mongo-express
    restart: always
    ports:
      - 21018:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
